name = "Lax604544Proofs"
defaultTargets = ["Lax604544Proofs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax604544"
path = "../concepts"

[[require]]
name = "Lax904597"
git = "https://github.com/PierreSenellart/descriptive-complexity"
rev = "5aef71b6365249121f68485b77de5e25e26f41bf"
subDir = "lax/np-core/concepts"

[[require]]
name = "Lax799700"
git = "https://github.com/PierreSenellart/descriptive-complexity"
rev = "5f34068ba7707478cd268f2316c295d7ea51a711"
subDir = "lax/np-catalog/concepts"

[[require]]
name = "Lax485149"
git = "https://github.com/PierreSenellart/descriptive-complexity"
rev = "eee50ee7b4c7bbf5f3d7efadda7518899cca280b"
subDir = "lax/logspace/concepts"

[[require]]
name = "Lax535992"
git = "https://github.com/PierreSenellart/descriptive-complexity"
rev = "89e95257ba3b6f37dae8a18b6fee583e62ecb749"
subDir = "lax/ptime/concepts"

[[require]]
name = "Lax564036"
git = "https://github.com/PierreSenellart/descriptive-complexity"
rev = "646a3b4286aec6f78457067508d69471f8822db6"
subDir = "lax/polynomial-hierarchy/concepts"

[[require]]
name = "Lax624099"
git = "https://github.com/PierreSenellart/descriptive-complexity"
rev = "f8eeb1ba6e95c4f8eea6f16401277e4b2124184e"
subDir = "lax/recursive-enumerability/concepts"

[[lean_lib]]
name = "Lax604544Proofs"
