import Mathlib.ModelTheory.Order
import Mathlib.Order.Defs.LinearOrder
import Lax904597.Problems
import Lax904597.Interpretations
import Lax904597.Relativized
import Lax904597.SecondOrder
import Lax904597.Classes
import Lax485149.Problems
import Lax485149.FirstOrderDefinability
import Lax485149.TransitiveClosure
import Lax485149.DeterministicTransitiveClosure
import Lax485149.ClassNL
import Lax485149.ClassL
import Lax535992.InflationaryFixedPoint
import Lax535992.ClassPTIME
import Lax134656.PartialFixedPoint
import Lax895169.ArithmeticLogic
import Lax945089.OrderFreeFirstOrder
import Lax945089.EhrenfeuchtGames
import Lax945089.PebbleGames
import Lax945089.Even
import Lax945089.Parity
import Lax945089.TransitiveClosureReductions

/-!
---
title: Invariance of formulas and inductions under pebble games
type: theorem
---
A first-order formula that fits in $k$ variables, its free variables and
its quantifier depth together, cannot separate two tuples related by the
$k$-pebble equivalence generated by agreement on atomic types. On bare
sets with at least $k$ elements each, two $k$-tuples with the same
equalities between coordinates are $k$-pebble equivalent, whatever the two
sizes: $k$ pebbles cannot count past $k$. And an inflationary induction
with variable budget $k$ takes the same value on two structures that have
$k$-pebble equivalent tuples.
-/

namespace Lax945089.PebbleInvariance

open FirstOrder FirstOrder.Language
open Lax904597.Problems Lax904597.Interpretations Lax904597.Relativized Lax904597.SecondOrder
open Lax904597.Classes
open Lax485149.Problems Lax485149.FirstOrderDefinability Lax485149.TransitiveClosure
open Lax485149.DeterministicTransitiveClosure Lax485149.ClassNL Lax485149.ClassL
open Lax535992.InflationaryFixedPoint Lax535992.ClassPTIME
open Lax134656.PartialFixedPoint Lax895169.ArithmeticLogic
open Lax945089.OrderFreeFirstOrder Lax945089.EhrenfeuchtGames Lax945089.PebbleGames
open Lax945089.Even Lax945089.Parity
open Lax945089.TransitiveClosureReductions

/-- A formula within `k` variables cannot separate `k`-pebble equivalent tuples. -/
axiom realize_equivK₂ :
  ∀ {L : Language.{0, 0}} {M N : Type} {k : ℕ} [L.IsRelational] [L.Structure M] [L.Structure N]
  [Finite M] [Finite N] {S : Set ((n : ℕ) × L.Relations n)} {α : Type} [Fintype α] {n : ℕ}
  (φ : L.BoundedFormula α n) (g : α → Fin k) (h : Fin n → Fin k), Function.Injective h →
  (∀ (i : α) (j : Fin n), g i ≠ h j) →
  (Finset.image g Finset.univ ∪ Finset.image h Finset.univ).card + qdepth φ ≤ k →
  RelsIn S φ → ∀ (v : Fin k → M) (w : Fin k → N), EquivK₂ (atomicAgreeOn₂ S M N k) v w →
    ((φ.Realize (fun i => v (g i)) fun j => v (h j)) ↔
      φ.Realize (fun i => w (g i)) fun j => w (h j))

/-- On bare sets, tuples with the same equalities are `k`-pebble equivalent. -/
axiom equivK₂_bare :
  ∀ {M N : Type} {k : ℕ} [Language.empty.Structure M] [Language.empty.Structure N] [Finite M]
    [Finite N]
  {S : Set ((n : ℕ) × Language.empty.Relations n)}, k ≤ Nat.card M → k ≤ Nat.card N →
  ∀ {v : Fin k → M} {w : Fin k → N}, (∀ (p q : Fin k), v p = v q ↔ w p = w q) →
    EquivK₂ (atomicAgreeOn₂ S M N k) v w

/-- An inflationary induction cannot separate two structures with `k`-pebble
equivalent tuples. -/
axiom ifpHolds_equivK₂ :
  ∀ {L : Language.{0, 0}} {M N : Type} {k : ℕ} {S : Set ((n : ℕ) × L.Relations n)}
  [L.Structure M] [L.Structure N] [L.IsRelational] [Finite M] [Finite N] (d : StepDef L),
  StepDef.VarBound d k → StepDef.UsesRels d S → qdepth d.out ≤ k →
  ∀ {v : Fin k → M} {w : Fin k → N}, EquivK₂ (atomicAgreeOn₂ S M N k) v w →
    (d.IFPHolds M ↔ d.IFPHolds N)

end Lax945089.PebbleInvariance
