import Mathlib.ModelTheory.Semantics
import Mathlib.Logic.Function.Basic
import Lax904597.SecondOrder
import Lax535992.InflationaryFixedPoint
import Lax945089.EhrenfeuchtGames

/-!
---
title: Pebble games between two structures
type: definition
---
In the $k$-pebble game on two structures $M$ and $N$, a position is a pair
of $k$-tuples, one in each structure. Two tuples agree on their atomic type,
relative to a family $S$ of relation symbols, when they satisfy the same
equalities between coordinates and the same relations of $S$ at every
selection of coordinates. A relation between $k$-tuples of $M$ and of $N$
has the back-and-forth property at a position when, whichever pebble the
spoiler moves and wherever, on either side, the duplicator can move the same
pebble on the other side so that the new position is again in the relation.
The $k$-pebble equivalence generated by an initial relation is the limit of
the chain of refinements that keep the positions of the initial relation
satisfying the back-and-forth property with respect to the previous stage:
the positions from which the duplicator can play forever. Unlike the rounds
of an Ehrenfeucht–Fraïssé game, the pebbles are reused, so the game bounds
the number of variables and not the quantifier depth.

For a simultaneous induction, $k$ is a variable budget when it covers, for
each relation variable, its arity plus the quantifier depth of its step
formula; and the induction uses relations of $S$ when the symbols of the
base vocabulary in its step formulas and output sentence all lie in
$S$.
-/

namespace Lax945089.PebbleGames

open Lax904597.SecondOrder Lax535992.InflationaryFixedPoint Lax945089.EhrenfeuchtGames

open FirstOrder

open Language Structure

/-- The relation symbols of a bounded formula all lie in the family `S`. -/
def RelsIn {L : Language.{0, 0}} (S : Set (Σ n, L.Relations n)) {α : Type*} :
    ∀ {n : ℕ}, L.BoundedFormula α n → Prop
  | _, .falsum => True
  | _, .equal _ _ => True
  | _, .rel R _ => ⟨_, R⟩ ∈ S
  | _, .imp f₁ f₂ => RelsIn S f₁ ∧ RelsIn S f₂
  | _, .all f => RelsIn S f

/-- The agreement family of the block expansion of a structure: the given
family on the base symbols, everything on the block symbols. -/
def blockRelsExtend {L : Language.{0, 0}} (S : Set (Σ n, L.Relations n)) (B : SOBlock) :
    Set (Σ n, (L.sum B.lang).Relations n) :=
  fun x =>
    match x with
    | ⟨n, Sum.inl r⟩ => ⟨n, r⟩ ∈ S
    | ⟨_, Sum.inr _⟩ => True

/-- The variable budget of a simultaneous induction: `k` covers each
variable's arity together with the quantifier depth of its step formula –
enough pebbles to hold the arguments and play out the quantifiers. -/
def StepDef.VarBound {L : Language.{0, 0}} (d : StepDef L) (k : ℕ) : Prop :=
  ∀ i, d.B.arity i + qdepth (d.step i) ≤ k

/-- The base relation symbols of a simultaneous induction – of its step
formulas and its output sentence – lie in the family `S`. -/
def StepDef.UsesRels {L : Language.{0, 0}} (d : StepDef L) (S : Set (Σ n, L.Relations n)) : Prop :=
  (∀ i, RelsIn (blockRelsExtend S d.B) (d.step i)) ∧
    RelsIn (blockRelsExtend S d.B) d.out

/-- A relation between `k`-tuples of two types: the positions of the
two-structure `k`-pebble game. -/
abbrev PebbleRel₂ (M N : Type) (k : ℕ) : Type :=
  (Fin k → M) → (Fin k → N) → Prop

variable {M N : Type} {k : ℕ}

/-- Pointwise implication of two-structure relations. -/
def PebbleRel₂.Le (E E' : PebbleRel₂ M N k) : Prop :=
  ∀ a b, E a b → E' a b

/-- The back-and-forth condition of the two-structure `k`-pebble game: the
pebble the spoiler moves, on either structure, can be answered on the other. -/
def PebbleBackForth₂ (E : PebbleRel₂ M N k) : PebbleRel₂ M N k :=
  fun a b => ∀ i : Fin k,
    (∀ c : M, ∃ d : N, E (Function.update a i c) (Function.update b i d)) ∧
    (∀ d : N, ∃ c : M, E (Function.update a i c) (Function.update b i d))

/-- One round of refinement. -/
def pebbleRefine₂ (E₀ E : PebbleRel₂ M N k) : PebbleRel₂ M N k :=
  fun a b => E₀ a b ∧ PebbleBackForth₂ E a b

/-- The descending refinement chain. -/
def pebbleStage₂ (E₀ : PebbleRel₂ M N k) : ℕ → PebbleRel₂ M N k
  | 0 => fun _ _ => True
  | n + 1 => pebbleRefine₂ E₀ (pebbleStage₂ E₀ n)

/-- **`k`-pebble equivalence between two structures**: the limit of the
refinement chain. -/
def EquivK₂ (E₀ : PebbleRel₂ M N k) : PebbleRel₂ M N k :=
  fun a b => ∀ n, pebbleStage₂ E₀ n a b

/-- Agreement on the atomic type between tuples of two structures: the same
equalities between coordinates, and the same base relations of the family `S`
at every selection of coordinates. -/
def atomicAgreeOn₂ {L : Language.{0, 0}} (S : Set (Σ n, L.Relations n)) (M N : Type)
    [L.Structure M] [L.Structure N]
    (k : ℕ) : PebbleRel₂ M N k :=
  fun v w =>
    (∀ i j : Fin k, v i = v j ↔ w i = w j) ∧
    ∀ {l : ℕ} (R : L.Relations l), ⟨l, R⟩ ∈ S → ∀ g : Fin l → Fin k,
      ((RelMap R fun p => v (g p)) ↔ RelMap R fun p => w (g p))

end Lax945089.PebbleGames
